### ISSUE TITLE
RIP Mac Version?

### ISSUE THREAD

**Issue by bbbarrow** [joeferraro/MavensMate#1006]
I try opening MavensMate on Mac Sierra--coded on it the day before--then go to open it the next day and get the attached error message: ReferenceError: logger is not defined.

To solve this problem would be heroic, it would really help me out.  Thanks.  I know that MavensMate is not going to be developed or really even supported any more, I am just hoping this makes it to someone who knows how to fix the error so I can at least use this awesome platform that I have learned and love using for as long as absolutely possible.  Thanks

v0.0.11-beta.7:

Sublime, but recently also installed Atom:

Latest:

Mac OSX Sierra 10.12.6 (16G29):

No:

40:

Several:

I try to open MavensMate desktop but get the following error:

![error](https://user-images.githubusercontent.com/24236058/30425329-075ad676-9906-11e7-8472-7049a94a8f44.jpg)

**Comment by kidtsunami** [comment]
Yikes mate. That's an exception handler gone wrong.

Can you double check that you've got some valid settings located at `ls ~/.mavensmate-config.json`?

**Comment by bbbarrow** [comment]
I might be doing this wrong, I have not developed a ton with command line and stuff, but I type that into the terminal and nothing happened, I also searched spotlight (cmd+space) for that exact text and found nothing.

Am I searching for the file in the wrong way?  Or would one of those two methods I just used produce something?  Thank you for responding at all, I appreciate it.  Thank you, B

**Comment by kidtsunami** [comment]
Ah my bad, just a quick explanation of what `ls ~/.mavensmate-config.json` means.

`ls` is the command for listing files in unix. [Here's a helpful page about it](https://www.linuxhelp.com/ls-command/). `~/.mavensmate-config.json` is a hidden file in your user's home directory (`~/`). 

The exception you're seeing is when it's attempting to read that file in. It's likely corrupted and doesn't parse into JSON properly. The above command ideally lists the file.

I would recommend moving that file out of the way so that mavensmate can try to re-create the config file properly.

Try the below steps:
1. Lets find the file to start before we try to move it:
`ls ~/.mavensmate*` (this lists all files in your home directory that have file names starting with `.mavensmate`.

Your terminal should look like this when you run it
```bash
yourComputerName:~ yourUserName$ ls ~/.mavensmate*
/Users/yourUserName/.mavensmate-config.json
```

2. After confirming that the file IS there. Lets just move it out of the way (we're not removing it just in case you've got some settings in there you want to remember).
`mv ~/.mavensmate-config.json ~/.mavensmate-config-backup.json`

After you do that, launch MavensMate Desktop, hopefully it detects that no settings file is there and recreates it with defaults.

**Comment by bbbarrow** [comment]
Whahhhh?  Dude it worked and I felt like a hacker boss tearing up the command line like that.  THANK YOU SO MUCH!  I really appreciate it.  I have grown roots with MavensMate, and it is such an awesome, time-saving tool, even compared to any of the other IDEs, and now you have just gifted me the ability to use this tool for as long as its current development state matches up with Salesforce.  Thank you again, I really appreciate it.  Usually when someone helps me with something like that, I like to leave good feedback or something, how would I do something like that?  Again, I really, really, really appreciate it, thank you so much, I am excited to be able to continue to use MavensMate on the mac side of my machine for a little while longer.  Thank you

**Comment by kidtsunami** [comment]
Ha, you can give the [MavensMate for VS Code](https://marketplace.visualstudio.com/items?itemName=DavidHelmer.mavensmate) extension a try. The VS Code IDE is pretty awesome and I can say that Salesforce is already moving the direction of having it's own extensions for VS Code, so even if MavensMate withers away, it will be because Salesforce is doing a good job of supporting VS Code.

Thanks for the kind words mate, I was happy to help! ❤️

**Comment by bbbarrow** [comment]
Ok, sounds good.  I am confused, does the MavensMate for VS Code still allow me to drive everything from MavensMate desktop and sublime text or atom?  Am I able to run that from the mac os?  If it is good I will give it a shot, I know that support is on its way out, but I am so comfortable with MavensMate as is and I don't want to learn something new unless it promises at least the same amount of easy access to functionality like MavensMate does.  The VS Code extension can be run on mac, though?  Thank you again, I just sat down to do a few last-minute coding items and was pumped that I was going to be able to use MavensMate on the mac side of my system again.  Thanks again, I really appreciate it

**Comment by bbbarrow** [comment]
Thank you again, just finished up my stuff, super pumped to still be using MavensMate on mac, I thought it was gone.  Thanks again

**Comment by kidtsunami** [comment]
@bbbarrow [VS Code](https://code.visualstudio.com/) is a free IDE from Microsoft that is very similar to Sublime and Atom (it actually has the same open-source core that Atom depends on). It's multi-platform, on Linux, Mac, and PC.

As of the moment, there are MavensMate plugins for Sublime, Atom, and VS Code that all interface with MavensMate Desktop. So I would recommend you download VS Code, install the MavensMate extension, and give it a go. If you've been using MavensMate, it should work just like you've been used to.

**Comment by bbbarrow** [comment]
That is awesome, and I am glad to see a minimalistic text editor from them, and maybe I will give that a shot when I have a lull or something, I'm so used to it the way that it is now.  What you said makes sense, I just read the description at the link you sent me https://marketplace.visualstudio.com/items?itemName=DavidHelmer.mavensmate and it says in the description that the aim of MavensMate is to have everyone live inside of Sublime Text for all of their Salesforce needs, what you said clarified it though.  Thank you again for the help, I will give vscode a shot, an best of luck in everything you have going on

**Comment by kidtsunami** [comment]
Haha whoops, that's what happens when you copy and paste a README... will have to fix that in the next release of MM for VS Code...

**Comment by bbbarrow** [comment]
No worries, it seems cool and worth checking out.  Thank you again, maybe I'll be having questions on VS Code, and maybe once I try it out, VS Code will be my new favorite text editor--I won't know unless I try.  Thanks, B
