### ISSUE TITLE
Auto code completion does now work

### ISSUE THREAD

**Issue by Rotnelson** [joeferraro/MavensMate#111]
code completion and code assistance for does not work properly.
- Custom classes methods does not show up.
- No search/suggestion for apex classes 

Object standard fields are not suggested.
E.g
Account a = new Account();
a.FirstN    
does not give any suggestion.

Datatype is not shown for field suggestion

I use Mac OS X 10.8.5
Mavensmate version 0.35.06
Sublime text 3 Build 3047

**Comment by hurrand** [comment]
I just opened a new issue myself for the same reason

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
