### ISSUE TITLE
Tooling API throws error in Database.com orgs

### ISSUE THREAD

**Issue by robertlmartinezjr** [joeferraro/MavensMate#112]
When creating a new project I receive a "405 Client Error: Method Not Allowed" error.  I'm on a Win7 64 bit.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
