### ISSUE TITLE
Test Results takes attempts to treat messages with some characters as HTML tags

### ISSUE THREAD

**Issue by capeterson** [joeferraro/MavensMate#127]
This prevents them, or a subset of their contents from rendering.
For example, a test that fails with the exception:
```
System.TypeException: Invalid conversion from runtime type LIST<ANY> to 
LIST<MAP<String,ANY>>
```
would render in MM's test runner as 
```
System.TypeException: Invalid conversion from runtime type LIST to LIST>
```
![test runner](https://f.cloud.github.com/assets/746698/1451378/ea01039c-4298-11e3-81d6-ac5530fbb7b8.png) due to not escaping HTML in the test's output.

MM 0.35.7
Sublime 3, build 3047
Sublime plugin v3.1.5

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
