### ISSUE TITLE
Can't perform diff to server version unless last editor is different

### ISSUE THREAD

**Issue by dshahin** [joeferraro/MavensMate#130]
When I try to save a file and it was last saved by another developer, I am presented with a nice side by side comparison diff.

I'd like to be able to do that with files I last edited as well, but can't figure out how to do it.  When I right click and select MavensMate->Synchronize with Server 
I get this error:
Result: [OPERATION FAILED]:Unsupported operation

I am using Sublime Text 3 and MavensMate for Sublime Text v3.1.5 on MavensMate 0.35.7

Is it possible to do what I want?

thanks,
Dan Shahin

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
