### ISSUE TITLE
Apex debug log user picklist limit

### ISSUE THREAD

**Issue by mshanemc** [joeferraro/MavensMate#134]
We have a very large number of users in our org (authenticated sites puts us >40k) but the debug user dropdown is only pulling part of our A list.  Could you make it quick search/filter, or let me type my user?

You may also run into the same thing with orgs where there are just plain tons of salesforce seats.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
