### ISSUE TITLE
Creating new project on existing folder gives wrong error

### ISSUE THREAD

**Issue by thajcak** [joeferraro/MavensMate#136]
I had checked out a project from github and tried to use it with MM. When I opened the project in SublimeText 3 the project contents was missing so I tried to create a new project through MM in the same place. This resulted in a "Unable to retrieve password from the keychain store." error message.

Once I removed the existing folder the error went away. In this case the error message wasn't useful and drove me in the wrong direction.

MM: 0.35.9
MM Plugin: 3.2.0
Sublime Text 3 b3047

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
