### ISSUE TITLE
components: can't specified custom wrapper object as type

### ISSUE THREAD

**Issue by sk29110** [joeferraro/MavensMate#138]
I have the custom wrapper clas as type for attributes in components and keep complainging type is not visible. it works on Force.com IDE but on sublime it fails with errror. V3.2.1

<apex:component >
    <apex:attribute name="selectedjobItem" description="" type="jobItem" required="true"/>

Result: [COMPILE FAILED]: (Job Detail) Type is not visible: jobItem  (Line: 1)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
