### ISSUE TITLE
[Feature Request] - Ability to refresh static resources.

### ISSUE THREAD

**Issue by noeticpenguin** [joeferraro/MavensMate#148]
![free_business_cards_-_enter_your_text](https://f.cloud.github.com/assets/376367/1683614/430eac90-5dc0-11e3-8256-1d8c44621c45.jpg)

^^^ for serious. 

At some point, whenever you get a chance, I'd like to request a small but, I think useful, feature. Right clicking on a resource bundle presents the option to refresh from server but it currently doesn't work, throwing an error about not being able to find a metadata type to .... anyway. Can we make that work ? That would make Resource bundles that much more super fantastical.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by aklef** [comment]
bump this because I want to able to refresh from the command pallet too.

>  is it possible to include that as a pallet command?

Answer is currently no, see picture below:

![image](https://cloud.githubusercontent.com/assets/1248568/15563041/bf60c772-22d2-11e6-8b3a-ddce2c840828.png)

Having an option to refresh the resource bundle 
![image](https://cloud.githubusercontent.com/assets/1248568/15563207/7867e93e-22d4-11e6-90d5-142d45ae70c6.png)
like this one from the context menu would be awesome!
