### ISSUE TITLE
unable to pull report/email template metadata on windows

### ISSUE THREAD

**Issue by mscholtz** [joeferraro/MavensMate#149]
when attempting to referesh after selecting reports/email templates in the Edit Project window, I am getting the following error:

Couldn't open [] because: coercing to Unicode: need string or buffer, list found {"body": "no element found: line 1, column 0", "stack_trace": "", "body_type": "text", "success": false}

This is in Sublime 3 (build 3047) and MM for windows 3.2.2, under Windows 7.  Looks like the same issue as this: https://github.com/joeferraro/MavensMate/issues/70, which says it was resolved.  Possible this fix wasn't included in the latest windows plugin?  It just downloaded an update this morning, so I think I've got the latest release.

Thanks!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
