### ISSUE TITLE
Enhancement request: Able to select multiple Apex test classes using the keyboard arrow keys

### ISSUE THREAD

**Issue by rakesh2020** [joeferraro/MavensMate#155]
Currently In windows if we want to run multiple apex test classes we need to manually select them using the Mouse clicks. Instead we need a functionality where we can select multiple test classes holding shift key and using up or down arrows.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
