### ISSUE TITLE
Win 7: Installation of Sublime Text Plugin Failed

### ISSUE THREAD

**Issue by boBNunny** [joeferraro/MavensMate#165]
I am receiving this error attempting installatino of MavensMate.  I tried the 5 steps listed on a similar case and they processed OK (although I had to add ..\ in front of GIT for the steps 3-5).  But this issue still comes up at the end of the installation.
![image](https://f.cloud.github.com/assets/6333901/1854313/4f4567f6-771a-11e3-8a6c-69de80710ca4.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
