### ISSUE TITLE
0.37.0: "Server raised fault: 'INVALID_ID_FIELD: Deployment failed:INVALID_CROSS_REFERENCE_KEY: No packages or unpackaged specified'"

### ISSUE THREAD

**Issue by dschloss** [joeferraro/MavensMate#175]
After updating the "Metadata Subscription List", hitting "Update Subscription", then "Update Project", this Error occurs:

"Server raised fault: 'INVALID_ID_FIELD: Deployment failed:INVALID_CROSS_REFERENCE_KEY: No packages or unpackaged specified'"

However, added Metadata is not showing up under Sublime "Folders" column.

Indexing Metadata doesn't help.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
