### ISSUE TITLE
Issue: F12 Go to Definition Doesn't work

### ISSUE THREAD

**Issue by grodno-mentoring** [joeferraro/MavensMate#177]
Hi,
Mavensmate for Sublime Text v3.3.5.
Windows 7.

Currently clicking on F12 does nothing.
Message : "unable to find ... ' method name ' " 

Expected result : go to the definition

Thank you.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by dineshkumar2** [comment]
same issue with me as well, i am using latest version 3126,  Expected result : go to the definition

if definition file is also open then it will work
