### ISSUE TITLE
error -10810, selecting new project and window does not appear mac os x 10.9.1

### ISSUE THREAD

**Issue by ktgerg** [joeferraro/MavensMate#180]
Hi,
when I try to create a new project via mavensmate plugin sublime text 3 the dialog never appears.

i turned on debugging and i see

Loading MavensMate for Sublime Text
Calling mm_interface
OPERATION: new_project
{}
executing mm terminal call:
/Applications/MavensMate.app/Contents/Resources/mm/mm -c SUBLIME_TEXT_3 -o new_project --ui
{}
response from mm: LSOpenURLsWithRole() failed with error -10810 for the file /Applications/MavensMate.app/Contents/Resources/mm/bin/MavensMateWindowServer.app.

{"body": "UI Generated Successfully", "body_type": "text", "success": true, "time": "0.2423110008239746"}

I'm pretty green on a mac os, so i'm not sure how to solve this issue, based on google searches it's probably some permissions issue or perhaps the install didn't work correctly.

You wouldn't happen to have manual install plug-in steps or even a laundry list of files i should see in the sublime text 3 packages directory?

thanks,

Katie

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
