### ISSUE TITLE
Issue with CronJobDetail Object

### ISSUE THREAD

**Issue by pbattisson** [joeferraro/MavensMate#181]
Hi, when trying to save a class with API v29 (or seemingly any version) I am getting the error:

 No such relation 'CronJobDetail' on entity 'CronTrigger'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. (Line: 48, Column: 32)

When attempting to save the following query

[SELECT Id, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType, NextFireTime FROM CronTrigger];

which has come from the Salesforce docs. I am using Sublime mate 2, with Mavensmate for Sublime Text 2.2.0 and Mavensmate.app v0.34. The same code saves fine in the browser.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
