### ISSUE TITLE
Feature request: Reuse Selected Deploy metadata

### ISSUE THREAD

**Issue by noeticpenguin** [joeferraro/MavensMate#189]
Given a complex deploy scenario where I've gotten it right once, I'd like to be able to "load" or somehow reuse the package.xml defined metadata selections. 

Totally a feature request.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
