### ISSUE TITLE
Unable to update project when behind proxy

### ISSUE THREAD

**Issue by girish989** [joeferraro/MavensMate#191]
We have proxy at work and we are not able to use mavens mate to refresh project from there because we are not able to configure proxy like we could in eclipse. 

Please help.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
