### ISSUE TITLE
Refreshing profiles from sandbox retreives empty profiles

### ISSUE THREAD

**Issue by TCS-JMI** [joeferraro/MavensMate#193]
Hi,
When I retreive un single profile (or all the profiles) with "Refresh from server", the profiles are almost empty:
Admin.Profile:
```
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <userLicense>Salesforce</userLicense>
</Profile>
```
I'm on MMST 3.3.5
Thanks
Regards, 
Jerome

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
