### ISSUE TITLE
[Feature Request] Ability to run SOQL Queries from UI

### ISSUE THREAD

**Issue by dirajkumar** [joeferraro/MavensMate#196]
It would be really helpful if we can run queries and modify records like Developer Console. Is there any plan for this feature in the near future?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
