### ISSUE TITLE
float division by zero on running Test Class

### ISSUE THREAD

**Issue by philhawthorn** [joeferraro/MavensMate#202]
After upgrading to 0.38.0 / MavensMate for Sublime Text v3.4.1 i get the following error when running Unit Tests:

![float](https://f.cloud.github.com/assets/2211627/2087234/0ee0c718-8e68-11e3-9588-b80d22602196.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
