### ISSUE TITLE
Version from 6 Feb 2014 disappeard from SublimeText after installation.

### ISSUE THREAD

**Issue by PawelWozniak** [joeferraro/MavensMate#207]
I was using MavensMate without any problems, then today 6 Feb after opening ST I have got info about new update, agreed to install it (closed Sublime text during update).
After restart ST said that cannot find code formating rules for Apex, then after second restart there is no MavensMate in Menu. 
Downloading from webpage complete installer and reinstalling does not restore it.

Shall I provide more info about config?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
