### ISSUE TITLE
Refreshing Permission Sets from server results in empty xml doc

### ISSUE THREAD

**Issue by mtetlow** [joeferraro/MavensMate#209]
I am having an issue when I right click on a permission set file and click "refresh from server". The file is rewritten but it only contains the top level <PermissionSet> tag, no child tags such as <ClassAccess>. When I pull down from the Mavensmate -> Edit Project interface the permission sets come down correctly with all the child tags.

Plugin: v3.3.5
App: 37.0
Sublime Text 3 Build 3059
OS X: 10.9.1

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
