### ISSUE TITLE
Debug Logs not pulling down from server on Linux

### ISSUE THREAD

**Issue by davidwoodytodd** [joeferraro/MavensMate#218]
After running "Run Async Apex Test for this Class", I receive the errors or success messages in the Mavens console, but no Logs were produced either within the project nor within the project folder. I did set a folder in User Settings for the mm logs. 

I am running Linux with Sublime3 and Mavens 3.4.4 &
mm_compile_with_tooling_api setting = true

Best Regards and thanks for everything
David

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
