### ISSUE TITLE
Not saving, stuck at compiling.

### ISSUE THREAD

**Issue by blaketanon** [joeferraro/MavensMate#223]
MM version 0.38.1
OSX 10.8.5

When saving anything I'm stuck with the below, this just randomly started happening.  What other info can I provide?

![screen shot 2014-02-20 at 11 18 45 am](https://f.cloud.github.com/assets/5342067/2220216/ecd8f656-9a4a-11e3-894f-1d6e3bf946ca.png)

**Comment by stefangoor** [comment]
I have seen a similar problem where the IDE stays trying to save files or run tests and never completes.  Even when I quit Mavensmate a background process (mm) seemed to keep going and eventually the API limit on the org is breach and the org is unusable for 24 hours without raising a support case.

Last time this happened I checked the org and noticed that it was giving an "Organization Administration Locked" error but Mavensmate didn't seem to pick this up and continued issuing API requests.  When we get this error it typically comes back to normal after a short time.

Could it be updated to fail when this happens rather than keep running?  We have had this happen in a few orgs.  It doesn't happen often but when it does it causes a lot of hassle as it prevents others working when the API limit is breached.

Many Thanks,
Stefan

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
