### ISSUE TITLE
ConnectedApp missing from Metadata Subscription List

### ISSUE THREAD

**Issue by schechter** [joeferraro/MavensMate#224]
There seems to be no way to work with a ConnectedApp through MavensMate?
These should be a category in the Metadata Subscription List.  They are available on version 29 and above of the API.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
