### ISSUE TITLE
Deploy To Server: Suggestion/Invalid Credentials

### ISSUE THREAD

**Issue by blaketanon** [joeferraro/MavensMate#226]
I put together a new project yesterday, and for the sake of time I didn't put in my security token.  When I went to deploy something this morning, the deploy window came up and displayed everything fine until I click the metadata tab.  Instead of showing classes, triggers, etc... there was just a checkbox for null - without any errors.  Quick look at debug showed the error.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
