### ISSUE TITLE
Configurable Server Proxy

### ISSUE THREAD

**Issue by short000** [joeferraro/MavensMate#227]
The resolution for #2 (MavensMate Server Proxy Issue) was to use the default system proxy. Unfortunately, this doesn't work if your company uses a Proxy Automatic Configuration (PAC) script. An undocumented workaround is to set the HTTP_PROXY and HTTPS_PROXY environment variables; however, toggling this back and forth can be a hassle. (I often switch networks even on the same project depending on if I am in the office or off-site.) mm_http_proxy and mm_https_proxy settings might be better. If they are blank then just fail-over to the environment variables. Then in the UI layer (Sublime and TextMate) allow proxies to be enabled/disabled or changed.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
