### ISSUE TITLE
Cannot open current page in Salesforce UI

### ISSUE THREAD

**Issue by tpais** [joeferraro/MavensMate#228]
When trying to open a specific file in a browser, the operation fails with the following error:

[OPERATION FAILED]: global name 'params' is not defined

Mavensmate v3.4.4
Sublime Text3 Build 3059
Python 2.7.5
OS X 10.9.1

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
