### ISSUE TITLE
cannot create MM project from git clone

### ISSUE THREAD

**Issue by brosiusad** [joeferraro/MavensMate#230]
We've been seeing a couple different problems with 'new_project_from_existing_directory' (i.e. "Create MavensMate Project...").  In both cases, we are trying to create a project from a folder that has been cloned from a git repo.  I will file these two issues separately (see #229 for the other bug)

The second issue is we are getting is that when one clones a git project directly into your MM workspace and then attempts to use "Create MM project...", the process will fail.  Instead, you have to clone to a different directory on your hard drive, then allow MM to copy the git clone into your workspace and delete the original.  I find it weird that MM would actually move the folder on disk, but that does appear to be what's happening.

It should be noted that I have been able to clone a git project into the workspace and then create a MM project from it in the past, so I'm guessing this is a newly-introduced bug.

When bug #229 doesn't strike, this workaround to clone into a non-Workspace directory seems to work.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
