### ISSUE TITLE
feature request: add support for SearchLayouts metadata type

### ISSUE THREAD

**Issue by brosiusad** [joeferraro/MavensMate#231]
It looks like this would go in the "childxmlname" section of "CustomObject" section in default_metadata.json?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
