### ISSUE TITLE
Unable to open project Ubuntu

### ISSUE THREAD

**Issue by idanblich** [joeferraro/MavensMate#234]
Hi , 
I can not open/switch project , no log error or anything .
Ubuntu 12.04 + MM v3.4.5 + chromium Version 32.0.1700.107 Ubuntu 12.04

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
