### ISSUE TITLE
User Settings - Displays blank file?

### ISSUE THREAD

**Issue by blaketanon** [joeferraro/MavensMate#236]
I just installed ST 3 and the MM plugin, but the user settings file is blank?  Any ideas?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
