### ISSUE TITLE
CallOptions/client not set at login

### ISSUE THREAD

**Issue by azam** [joeferraro/MavensMate#237]
It would be better if MavensMate set the client string upon login so that sysadmin can track session usage/API calls by application id. Bonus point if that client string can be overwritten from mavensmate.sublime-settings .

Good work guys!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
