### ISSUE TITLE
CustomObject in Project Metadata doesn't example

### ISSUE THREAD

**Issue by peter-yao** [joeferraro/MavensMate#238]
Hi -

I'm using v3.4.5 on Windows 7 and can't add CustomObjects after a recent plugin upgrade and object rename in Salesforce.

Unfortunately, I'm not sure which caused the problem, but I've since tried removing CustomObjects from the subscription and project and then re-adding it, but still get a UI that looks like this:

![image](https://f.cloud.github.com/assets/6842801/2313012/a73bfa5a-a303-11e3-81f7-96b974d70fd3.png)

I've tried to create a new Project to sync CustomObjects, and can expand the folder, but it only has one option ("null") under it.

How should I debug this?

Thanks for the tool - it's made a huge difference in my projects.

Peter

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
