### ISSUE TITLE
Feature Request: Metadata status during deploy.

### ISSUE THREAD

**Issue by noeticpenguin** [joeferraro/MavensMate#239]
A user on Salesforce.stackexchange.com was asking how to get mm's deploy to server screen to display a "status" field, like the eclipse tool does. (tired of the comparisons yet?) [link to stack exchange q/a](http://salesforce.stackexchange.com/questions/29308/force-com-ide-deployment-alternative) 

I explained i didn't know of a way currently, but that I would open a feature request issue on github.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
