### ISSUE TITLE
[Feature Request] View for Deploy->Metadata by last modified date-time

### ISSUE THREAD

**Issue by mattisdada** [joeferraro/MavensMate#251]
I would love to see an additional view inside the Deploy->Metadata section to view the last modified items, this would make it substantially easier to do "feature migrations" and would minimize mistakes (forgetting to tick an item is the reason 95% of my failed deployments fail).

It's the biggest flaw with the Web UI for Salesforces Deployment, and Maven Mate mitigates this issue by being reasonably quick to get into subfolders, but it's still easy to forget items.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
