### ISSUE TITLE
Error when fetching Checkpoint: global name 'shutil' is not defined

### ISSUE THREAD

**Issue by JolandaVerhoef** [joeferraro/MavensMate#253]
When fetching a checkpoint I get the following error:

global name 'shutil' is not defined

In my User Preferences I have "mm_log_level" : "INFO".
However, there are no logs written to the log file.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
