### ISSUE TITLE
[OPERATION FAILED] if .git directory is present

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate#257]
Within my project I have a .git directory and I have realized that this causes OPERATION_FAILED messages with no explanation when compiling the whole project. I looked into the logs and found that MavensMate had no access to some directories in the .git folder and always threw this message up!

This meant that my compiles were taking on average 15 minutes and were always returning [OPERATION_FAILED] notifications regardless of success or failure.

Removing the .git directory allowed me to complete the compile with a successful result and in just 2-3 minutes! Finally!

Only problem is... I want to put the .git directory back into my project and don't want to have to keep moving it about every time I compile the project.

How can I get MavensMate to ignore .git?

> v3.4.6 for ST3059
> Windows 8.1

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
