### ISSUE TITLE
Enhancement Request: Ability to delete custom fields on objects

### ISSUE THREAD

**Issue by seanrussell** [joeferraro/MavensMate#259]
Currently, the mm delete command only allows the specification of a file or list of files for deletion. It would be really useful if we could specify a specific custom field on an object for deletion.

**Comment by smohyee** [comment]
This is related to this issue: https://github.com/joeferraro/MavensMate/issues/327

SF API handles deletions and other 'destructive' commands via a 'destructivechanges.xml' file which I think would be pushed along with the package.xml file that MavensMate automatically creates and maintains for you as you build a project. It doesn't look like MavensMate has any functionality for automatically creating/writing the destructivechanges.xml file.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
