### ISSUE TITLE
Tests Runner Doesn't Show Skipped Tests

### ISSUE THREAD

**Issue by dhoechst** [joeferraro/MavensMate#261]
When a test will cause a callout to be performed and a mock hasn't been set, the test method doesn't show in the test runner UI after running tests for the class. In Salesforce's web UI, I see that tests have been skipped.
![mavens ui](https://cloud.githubusercontent.com/assets/1051263/2624519/7bad36b2-bd46-11e3-9460-46aa75422946.png)
![web ui](https://cloud.githubusercontent.com/assets/1051263/2624520/7d8f974a-bd46-11e3-9e43-feafd33ccf68.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
