### ISSUE TITLE
request: mm_ignore_managed_metadata should apply to installed packages, not local packages

### ISSUE THREAD

**Issue by mscholtz** [joeferraro/MavensMate#263]
currently it appears that the setting mm_ignore_managed_metadata applies to all namespaced metadata, whether it's from an installed package, or you're developing a managed package in your org.

I humbly request that you either include two settings for this, or, even better, just always show metadata from your own local namespace, and use this setting to only apply to installed packages.  I can't think of a situation where you'd want to hide your own package.

otherwise if you're an app developer, you have to choose between not seeing the code for your app, or littering your other projects with metadata from installed packages.  and since this setting is "true" by default, it makes for some confusion when your locally-packaged metadata does not initially appear.

thanks!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
