### ISSUE TITLE
Summery of passes apex tests

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate#270]
Request:
Would it be possible to include a summary "x/x passed" at the top or bottom of the Apex Tests page? To alleviate my having to carefully scroll the whole list of tests to see if any came back with failures?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
