### ISSUE TITLE
Cannot deploy document.

### ISSUE THREAD

**Issue by geeljire** [joeferraro/MavensMate#275]
When I save a document, I get this error:

```
Result: [DEPLOYMENT FAILED]: unpackaged/package.xml: An object '...project_path\src\documents\SharedDocuments\CommunityHeader1_04.html/CommunityHeader1_04' of type Document was named in package.xml, but was not found in zipped directory
```

The document's name is `CommunityHeader1_04` and it contains the file `CommunityHeader1_04.html` which I'm trying to update.

I'm on Windows 8.1 x64. Let me know if I can provide more info.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
