### ISSUE TITLE
The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app

### ISSUE THREAD

**Issue by RosaLozano** [joeferraro/MavensMate#284]
I am using Windows 7 with:
MavensMate for Sublime Text v3.5.0
SublimeText 3 Build 3059

I have tried to access Sandbox, and my Developer's version. I get the same error..
This is the first time I am using MavensMate.. 

I have updated my User Settings as:
"mm_workspace" : "c:\\IDE",
"mm_http_proxy" : "http:\/\/web-proxy.company.com:8080",
"mm_https_proxy" : "http:\/\/web-proxy.company.com:8080",
"mm_api_version" : "30.0",

Any idea?

Thank you
-Rosa Lozano

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
