### ISSUE TITLE
Deploying Report Fails

### ISSUE THREAD

**Issue by boxfoot** [joeferraro/MavensMate#285]
Deploying an open report file using the `CTRL-SHIFT-S` shortcut fails with the following message:

> [DEPLOYMENT FAILED]: unpackaged/package.xml: An object 'c:\Users\username\path\to\project\src\reports\Report_Folder\Report_Name.report/Report_Name' of type Report was named in package.xml, but was not found in zipped directory

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
