### ISSUE TITLE
Cannot create new project in x64 Windows 7 Enterprise Edition

### ISSUE THREAD

**Issue by nsanthosh718** [joeferraro/MavensMate#288]
Hello Joe,

I tried to install Mavensmate using manual install process and when I tried to create new project from sublime text, Mavensmate UI does not show up. Below is the log

Loading MavensMate for Sublime Text
Calling mm_interface
OPERATION: new_project
{}
{}
response from mm: Traceback (most recent call last):

  File "C:\users\myuser\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py", line 4, in <module>

    reload(sys)

NameError: name 'reload' is not defined

Can you help? 

Thanks,
Santhosh

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by nsanthosh718** [comment]
Hey Joe,

I haven't been following this issue but Yes, this is resolved and I like the new features in Mavensmate. I think it is more robust and faster than previous versions. Great work!

Thanks,
Santhosh

**Comment by joeferraro** [comment]
@nsanthosh718 wow great!
