### ISSUE TITLE
MavensMate is damaged and can't be opened?

### ISSUE THREAD

**Issue by terencelo** [joeferraro/MavensMate#291]
I've unzipped MavensMate to the Application directory on my mac.  When I right click to open it, I receive the following error message.

Note that I've tried to re-download the file and copied it with the same problem.  Any idea what's up or what I'm doing incorrectly?

I'm on OS X 10.8.5

![screen shot 2014-06-10 at 12 57 25 pm](https://cloud.githubusercontent.com/assets/34767/3233647/6290c4f2-f0c0-11e3-9f42-52825c1d52e4.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
