### ISSUE TITLE
Custom Domain for deployment

### ISSUE THREAD

**Issue by sebinio** [joeferraro/MavensMate#294]
Hi Joe,

When creating a connection for deploying code please can we have ability to create domain URLs to cater for custom domains. Got a client now who has blocked login.salesforce.com and can only deploy to client.my.salesforce.com, so unfortunately a change-set is required.

https://help.salesforce.com/HTViewHelpDoc?id=domain_name_overview.htm&language=en_US

Thanks Seb

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
