### ISSUE TITLE
Receiving error "unknown url type:"

### ISSUE THREAD

**Issue by apschwartz** [joeferraro/MavensMate#296]
I've just upgraded to MavensMate.app 0.38.4.  Upon saving a file in Sublime 3.0 an MM window is opening asking me to re-enter my credentials in order to upgrade the project.  I am specifying a Custom URL.  Upon clicking Upgrade Project the upgrading window displays for a moment followed by the error message "unknown url type:"

If I choose a standard SF endpoint I receive a (expected) login failure message.

Is Custom URL for an sfdc endpoint supported in the latest release?

Thank you.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
