### ISSUE TITLE
Referesh file from local desk will it save into server?

### ISSUE THREAD

**Issue by sarava77** [joeferraro/MavensMate#306]
Hi All,

I have modified my source file(Trigger or classes) in local desk.When I do 'Refresh folder' it will load my changes into my sublime text editor but it didn't save into saver(like force.com ide).Is there any way to do it.If its please let me know.

Thanks in advance!!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
