### ISSUE TITLE
Enhancement: Async Test Runner Should Report Test Count and Passed Tests

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#307]
Currently the Async test runner only reports the test failures and none of the passed tests.

Ideally the async test runner would report a summary of how many failures and passes there were and print out passed tests.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
