### ISSUE TITLE
Syntax highlighting not marking "testmethod" as identifier

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#311]
Currently the `testmethod` identifier isn't recognized correctly by syntax highlighting. Strangely this seems to happen initially until the function parens are put in place.

![screenshot 2014-07-14 11 30 45](https://cloud.githubusercontent.com/assets/841021/3574297/a929651e-0b7c-11e4-8309-bac3676b3d96.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
