### ISSUE TITLE
Changing the template sources

### ISSUE THREAD

**Issue by InspectorSpacetime** [joeferraro/MavensMate#313]
Hello,

I'm attempting to change the template sources from the default GitHub repository to a clone that I've made elsewhere on the web on a Mac with version 0.38.4 of MavensMate.

I've noticed that **mm_template_location** only supports local and GitHub repositories. I would like to add support for other web sources. In MavensMate-SublimeText's util.py lines 99-124 from the working copy I can see the package.json file is downloaded from GitHub. Could you please tell me where the code that downloads the individual templates from GitHub is?

Presumably it uses the package.json as a reference but I've been unable to find the code that downloads the templates so I was wondering if it could be in one of the other packages that makes up MavensMate.

Thanks so much for your help.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
