### ISSUE TITLE
Enhancement: Add Support for Setting Debug Log Levels for Async Test Run

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#315]
Test method debug logs get so, so long. Thankfully we've got controls to change the levels using the Test Runner.

The async test runner is equally awesome, but doesn't have this functionality. A great enhancement would be to have some config settings that controlled the debug levels for async. Or failing that, set them to APEX_CODE: Debug by default.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
