### ISSUE TITLE
Error trying to use API 31

### ISSUE THREAD

**Issue by carolinaruiz** [joeferraro/MavensMate#321]
Hey,

This might not be a bug, but i've been working on a project that currently requires API 31 from Salesforce. I modified the config 

	//set to desired Salesforce.com API version (tooling api functionality requires 27.0+)
	"mm_api_version" : "31.0",

In both User and Default and get the following error message when creating a new project to an org. 

ERROR:suds.umx.typed:Schema:0x105682638 (raw) (model) {"body": "Type not found: 'done'", "body_type": "text", "success": false}

MM version 3.5.2
Sublime build 3059

Thanks.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
