### ISSUE TITLE
Code coverage results different in Mavensmate and developer console

### ISSUE THREAD

**Issue by teclsx** [joeferraro/MavensMate#324]
After i run a test for one of my class, the Apex coverage results for unit tests in the Mavensmate and the developer console are different, the result is as below.  I'm wondering what could cause the differences?  Is Mavensmate run test different from the run test in the Salesforce?

Mavensmate:  74% covered
Developer Console: 54% covered

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
