### ISSUE TITLE
Unable to create project - SSLError(SSLError(1, '_ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'),) is not JSON serializable

### ISSUE THREAD

**Issue by Eric-He** [joeferraro/MavensMate#326]
I am running MavensMate on Windows 7 behind the company firewall. I set the http.proxy and https.proxy in git config --global, and also added the http_proxy and https_proxy to environment variables, and specified the mm_http_proxy and mm_https_proxy in mavensmate.sublime-settings-User. The http_proxy format is http:\\username:password@server:port, the https_proxy format is https:\\username:password@server.:port. The MavensMate was successfully installed, but when I tried to create a project, I got the following error meessage:

SSLError(SSLError(1, '_ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'),) is not JSON serializable

I really like ManvesMate and want to use it with Sublime Text, so is there anyone can help me out of this issue? Thanks in advance!!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
