### ISSUE TITLE
Add support for destructiveChanges.xml or the like

### ISSUE THREAD

**Issue by ckoppelman** [joeferraro/MavensMate#327]
It would be terrific to be able to remove metadata through destructiveChanges.xml.  Even if this were not able to be easily generated, it'd be great to expose that functionality through MavensMate.

**Comment by smohyee** [comment]
Another vote for this. SF gives instructions for deploying the destructiveChanges.xml file via ANT, but I wonder if it's possible to create a destructiveChanges.xml file in MavenMate's directory and push that to the SF org in a similar manner?

**Comment by ckoppelman** [comment]
@smohyee Can you try it out and see?

**Comment by smohyee** [comment]
I will report back if/when I get around to messing with it. I don't have any experience working with the destructiveChanges.xml file though, so I'm going to have to learn about how its usually deployed. I'm checking out workbench.developerforce.com now as an alternative tool.

**Comment by smohyee** [comment]
@ckoppelman I gave it a shot, don't think it can be made to work without MavensMate developing that feature.

My understanding is that when you use the 'Deploy to Server...' User Interface, MavensMate will build a separate deployment package from your local project directory based on the metadata you select to deploy. It will create a new package.xml file to go with that deployment, and drop it all in its own 'deploy' folder in your local directory before pushing it to SF via the metadata API. 

Since it builds the deployment package on the fly based off your selections in the UI, I can't see a way to stick the destructiveChanges.xml in the deploy folder (the folder is created and sent to SF servers all after you hit the 'Deploy to Server' button). But I'm guessing this is all that's needed.

I might reach out to Joe about the possibility of contributing to this feature. I could see development for this happening in two stages:

1. Quick and Dirty: allow a manually created destructiveChanges.xml file to be included in MavensMate deployments (maybe just have a button on the Deploy to Server UI that allows the addition of the file?)

2. Fancy: build the destructiveChanges.xml file using a MavensMate UI (selecting fields and custom objects just like you can when selecting metadata for creating a new project)

**Comment by ckoppelman** [comment]
From looking around the backend, I think all that needs to happen is a change to Deploy.compileWithMetadataApi to be overloaded to accept 

```js
{package: [files, subscriptions],
 destructiveChangesPre: [files, subscriptions],
 destructiveChangesPost: [files, subscriptions]}
```

Then you can new `Package`s with those in `Deploy.stage`, and then you can add all `destructiveChanges*.xml` to `unpackaged.zip`.

But I'm really not sure how the UI flow would have to change.  Would there be two more tabs? Ick.

**Comment by joeferraro** [comment]
Hey guys, thanks for the feedback on this one. There's a lot of work being done right now to prepare for the upcoming MM for ST 5.0 release. I can't say for sure whether this will make it in, but it's been duly noted.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
