### ISSUE TITLE
Question: Key Bindings for Mavensmate commands

### ISSUE THREAD

**Issue by DavidACL** [joeferraro/MavensMate#328]
Question about binding MM commands from the command palette to specific keyboard shortcuts:

(Note: I'm on Win7)

I tried to use the keys property on the Mavensmate user settings object, and was unable to get the newly bound keyboard to fire any Mavensmate command.  Is this a use that is not supported, not supported on windows, or am I experiencing a unique issue?

Example user settings where F7 shortcut does not work (likely because this is a User Settings object and not the Key Bindings - User object as seen under Preferences menu item):

{
	"mm_compile_with_tooling_api" : true,

	"auto_match_enabled": false,
	"mm_hide_panel_on_success": false,
	"mm_compile_scroll_to_error": true,
	"mm_autocomplete": true,

	 "keys": ["f7"], "command": "run_apex_script" 	
}

Is this sort of command mapping possible in MM in Windows (or even on Mac)? 

Thanks.

-David

**Comment by cnaccio** [comment]
I was able to bind ctrl+r to the run_apex_script command without any troubles. See my user key mapping below:

    [
	    {"keys": ["shift+space"], "command": "run_macro_file", "args": {"file": "Packages/User/Macros/CompleteLineWithSemicolon.sublime-macro"}},
	    { "keys": ["ctrl+keypad0"], "command": "reset_font_size" },
	    { "keys": ["ctrl+r"], "command": "run_apex_script" }
    ]

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
