### ISSUE TITLE
When all tests in class are skipped, no results shown in Test Runner UI

### ISSUE THREAD

**Issue by john-brock** [joeferraro/MavensMate#330]
Repro: 
1) create method with http callout
2) write test class for that method 
3) run test class using Test Runner 
Actual Behavior:
-- No results will be shown

Expected Behavior:
-- Error message that test was skipped should be displayed rather than simply having zero results 
NOTE: this is the behavior in the Apex Test Runner UI in Salesforce

There is a possibility that when a test is skipped no results are returned and thus you have no data to build error messages / results which is causing this behavior.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
