### ISSUE TITLE
Double "About MavensMate"

### ISSUE THREAD

**Issue by brettbatie** [joeferraro/MavensMate#336]
I'm using Linux MavensMate and have it installed by adding the Github repository as a package control repository, so I'm on the latest version that is in Github. This is minor but I see two "about mavensmate" options in the menu. See attached image.
![menu_086](https://cloud.githubusercontent.com/assets/3673593/4126865/bb739b9a-32f0-11e4-92b2-1e077816eaf7.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
