### ISSUE TITLE
Unable to eliminate some fields from Contact or Account

### ISSUE THREAD

**Issue by ckoppelman** [joeferraro/MavensMate#337]
I get the following error when trying to edit my project to exclude certain fields from Account and/or Contact:

    Couldn't open [] because: coercing to Unicode: need string or buffer, list found {"body": "string indices must be integers, not str", "stack_trace": "Traceback (most recent call last):\n File \"mm.request\", line 93, in execute\n File \"mm.commands.project\", line 101, in execute\nTypeError: string indices must be integers, not str\n", "success": false}

See #70 and #156 as well as #149 for a similar error.

Mac OSX 10.9.4
Sublime Text 3 Build 3065
MavensMate for Sublime Text v3.5.4
MavensMateWindowServer Version 1.0 (1)
MM.app v0.38.4

Is there a workaround?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
