### ISSUE TITLE
Cannot create project - IE 11 freezes; Chrome give Access Denied

### ISSUE THREAD

**Issue by kennesk** [joeferraro/MavensMate#339]
I have cloned a git project locally and dragged it into Sublime. Then I try to create a MavensMate project. IE 11 opens up automatically and I enter valid credentials. Then it just freezes. So I tried Chrome and I get Access Denied there. I've tried many things and nothing works. Can you please help? Here's the end of the log:

result from command execution
[Error 5] Access is denied
<type 'exceptions.WindowsError'>

---------------------

---------------------
RESPONDING TO REQUEST
---------------------

{"body": "[Error 5] Access is denied", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.project\", line 150, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.project\", line 42, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 122, in retrieve_and_write_to_disk\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 287, in move\nWindowsError: [Error 5] Access is denied\n", "success": false}

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
