### ISSUE TITLE
Not able to run UnitTests

### ISSUE THREAD

**Issue by cwarheit** [joeferraro/MavensMate#343]
When I try to run Unit Tests, I get an error telling me that a class needs to be recompiled, but then the stack trace error seems to be pointing me to an issue in Python:

Stack Trace
OrderedDict([(u'@xsi:nil', u'true')])

Both MavensMate and my Salesforce Sandbox instance (Winter '15) updated today.  Anyone else seeing this error?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
