### ISSUE TITLE
Object Deployment log missing field names

### ISSUE THREAD

**Issue by rafiepstein** [joeferraro/MavensMate#344]
After successful deployment of an object, the log (in the browser) shows a list f what is supposed to be objectname.fieldname, but fieldname is always "object".
Fr example Del-Registration_Item__C.object.
The result is a meaningless long list with identical items.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
