### ISSUE TITLE
Why can I not save a controller if the page has errors?

### ISSUE THREAD

**Issue by c4tch** [joeferraro/MavensMate#346]
Hi,
I have a page and a controller. Both are new and under development.
I create a new function on the controller, but the page is not complete. I know the apex I have is valid, and I know the page has some errors.

When I save the controller, the save fails due to the error on the page. This is creating a very slow workflow. Why do I have to remove the Page errors before I can compile the class? Is mavens mate dependent on all files being compilable before it saves the one I am working on?

Operation: Compiling: G2O_AccountTeamPanel_VFCx.cls
Timestamp: Thu, 11 Sep 2014 11:51:44
   Result: [COMPILE FAILED]: (G2O_AccountTeamMember_Panel) Unknown property 'AccountStandardController.deleteATM'  (Line: 1, Column: -1)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
