### ISSUE TITLE
Error 5 Access Denied

### ISSUE THREAD

**Issue by patiilabhijit** [joeferraro/MavensMate#353]
Hi,

When i create 1st project it gets created successfully, but when i tried to create 2nd project i get error [Error 5] Access Denied

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
