### ISSUE TITLE
Unable to retrieve password from the keychain store

### ISSUE THREAD

**Issue by patiilabhijit** [joeferraro/MavensMate#357]
Hi,

I am getting "Unable to retrieve password from the keychain store"  error whenever i am trying to create new class or trying to run Apex test report.

I am using Windows 7. Is there anywhere i can change project password, because if i am trying to edit project it is not opening in chrome.

Thanks,
Abhi

**Comment by garyspencer** [comment]
Try this fix:

https://github.com/joeferraro/MavensMate-SublimeText/issues/705#issuecomment-146154726

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
