### ISSUE TITLE
Mavensmate doesn't fetch logs correctly

### ISSUE THREAD

**Issue by lance-shi** [joeferraro/MavensMate#364]
I am using Mavensmate for sublime on Windows. The version is v4.0.2. I followed the instructions:
1. I clicked MavensMate > Debugging > New Trace Flag, and created a user debug flag for me. It was created successfully. 
2. I logged into Salesforce and performed some VF page operations which should generate some logs. 
3. I went back to MavensMate and clicked fetch log. It says success but the log folder is not generated.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
