### ISSUE TITLE
Blank deployment results, code not deployed

### ISSUE THREAD

**Issue by sebinio** [joeferraro/MavensMate#367]
Hi Joe, since I've upgraded to the latest mavensMate 0.38.6 and v4.0.2 for Sublime I'm no longer able to deploy. This is happening with all projects. I select the classes I want to deploy, click deploy, the loading GIF appears, then disappears and the button changes back to Deploy to server and the code hasn't been deployed. The deploy result are blank. I've tried a number of combinations of selecting and deselecting the Roll back on errors, validate only and run test. No result is displayed and no deployment happens.

**Comment by mkpartnersDev1** [comment]
I get this a lot too.  It seems to happen when Salesforce is not responding in time.

**Comment by frontendloader** [comment]
I know this might not apply to everyone in this thread, but when I get this issue I can fix it by deleting/re-adding the credentials for my target instance.

**Comment by rajuramaswamy** [comment]
I too think so. I did the same last week and it started   working.
Thanks for the info.
Raju Ramaswamy

**Comment by yannickglt** [comment]
Thank you @frontendloader. That worked for me too.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
