### ISSUE TITLE
Unable to edit project

### ISSUE THREAD

**Issue by IvanRibakov** [joeferraro/MavensMate#369]
When navigating to MavensMate -> Project -> Edit Project... I get window with blank detail fields and buttons like "Update Project" or "Update Credentials" are unresponsive (no actions seems to take place when I click on them).

OS: Mac OS X Yosemite 10.10
Sublime Text 3 build 3065
MM v4.0.2 (although this issue was present before I updated to 4.0.2)

![image](https://cloud.githubusercontent.com/assets/3639958/4934610/1e2a5730-65a3-11e4-8e25-55a3b941a2b4.png)

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
