### ISSUE TITLE
VF autocomplete of closing tags ignores self closing tags

### ISSUE THREAD

**Issue by devrieslex** [joeferraro/MavensMate#371]
If I have this in my page:

    <apex:outputPanel>
       <apex:pageMessage summary="message" /> 

I would expect to get `</apex:outputPanel>` if I type `</` at the bottom. Instead, I get `</apex:pageMessage>`

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
