### ISSUE TITLE
MM stopped working

### ISSUE THREAD

**Issue by v100** [joeferraro/MavensMate#372]
Had a problem yesterday where the file was saving showing success but the page was not updated on SFDC. Tried reset containers etc but still a problem.
I have tried to refresh the project and it returned the error that sublime was not running or there was problem with the app.
I eventually removed MM and tried to reinstall. The message said it installed but no menu appeared. Tried this several times, have since removed and reinstalled Sublime too.
Still when i try to install MM the message on the status bar shows installed but no menus appear. It does not show in the package control, and it continues to show in the install menu.
Anyone any idea why i am stuck? Thanks

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
