### ISSUE TITLE
Deployed resource bundle always private

### ISSUE THREAD

**Issue by chasd00** [joeferraro/MavensMate#373]
Every time I deploy a resource bundle it gets set to private even if it's already set as public in the org.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
