### ISSUE TITLE
Unicode/Font Awesome display issue for Deployment UI on Firefox

### ISSUE THREAD

**Issue by Bard09** [joeferraro/MavensMate#377]
Looks like there's an issue with Firefox and the Font Awesome fonts on the Deploy page.  Here's a screenshot of my experience:

![mavensmatedeployfirefox](https://cloud.githubusercontent.com/assets/9892295/5151712/2ad8c570-7197-11e4-8850-4ae9d3380704.png)

Firefox debug info displays the following error:

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol."

According to some random Google searches, adding the following to the Deploy page HTML might resolve the problem...?  No idea.

`<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">`

Other info:

Firefox v33.1.1
Windows 7 64-bit
Sublime Text 3 64-bit
MavensMate 4.0.2

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
