### ISSUE TITLE
Deploying Doesn't Push Object Files to Server

### ISSUE THREAD

**Issue by pescjjj** [joeferraro/MavensMate#382]
Hello,

I've been happy using MavensMate and Sublime for the past couple of weeks. But I ran into an issue today that forced me to open Eclipse, and perform the operation there. I did a Deploy to Server and everything completed successfully, but non of my .object files were pushed. I confirmed that by looking at the list of deployed files and conforming that the objects on the server didn't reflect my latest changes.

.object is included in the mm_apex_file_extensions section of my settings file. Is there some other place I should look?

Thanks,
  Joe Pescatello

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
