### ISSUE TITLE
How to refresh single file from server that doesn't exist locally?

### ISSUE THREAD

**Issue by feenst** [joeferraro/MavensMate#383]
To get updates from the server today, I am right clicking on the project root folder in Sublime Text 3 -> MavensMate -> Refresh from Server.

Is there a better way to retrieve a single file from the server that hasn't yet been retrieved? Refreshing all of the pages, classes and triggers from my org takes several minutes.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
