### ISSUE TITLE
Enhancement: Status indicator for files not saved to server

### ISSUE THREAD

**Issue by pescjjj** [joeferraro/MavensMate#386]
Would be great if there were a status indicator that showed if you haven't saved a file to the FDC server. It might work like the indicator on the file name that shows when you've edited a file but haven't saved it locally.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
