### ISSUE TITLE
Problem with deployed object

### ISSUE THREAD

**Issue by adashko** [joeferraro/MavensMate#387]
We have 4 custom deployed object (object is marked as 'deployed' if these objects included in release package and package was uploaded to appExchange). MavensMate cannot receive these objects using metadata and package.xml doesn't contain these objects.

Maybe you can add 'select all' checkbox (as child for CustomObject element) to metadata graph (emulate '<members>*</members>' setting for package.xml)?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
