### ISSUE TITLE
mm_workspace with python (without Sublime Text) installation

### ISSUE THREAD

**Issue by aadoello** [joeferraro/MavensMate#388]
Hello all,

I installed mm through python pip as I want to build my own functionalities through mm API, but I can't find where to specify the workspace. Whenever I try to launch an mm action it complains about the mm_workspace variable, but I have no idea where to set it without Sublime Text. I have found two config files (one for atom, one for st3) and set it there, but none of them worked.

Can anyone tell me how to set it properly without using Sublime Text? :-)

Thanks in advance!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
