### ISSUE TITLE
Sound after test run from test runner ui taken from facebook chat?

### ISSUE THREAD

**Issue by rpost** [joeferraro/MavensMate#389]
As mentioned in title: does this sound is taken directly from facebook?
Event if no it's too similar imho and it may be confusing especially if you have facebook opened during coding :).

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
