### ISSUE TITLE
Refresh from server hangs Sublime Text 3.0

### ISSUE THREAD

**Issue by saurabhkul** [joeferraro/MavensMate#399]
Hello,

When i click "Refresh from server" in Mavensmate to get latest Salesforce code it hangs Sublime Text 3.0 64bit. It consumes large amount of CPU usage as well. I cannot do anything after this. I re-installed Sublime Text & Mavensmate multiple times. But no luck. Please help me out. Thanks in advance.

Saurabh

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
