### ISSUE TITLE
It would be great to have a key combo for "Clean Project" action

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate#423]
Currently every time a project needs to be refreshed/cleaned, user has to go through the menu and mouse clicks.. It would be great to have a key combo for that.

**Comment by ralphcallaway** [comment]
@OlegForce depending on what text editor you're using you can probably set that up

for sublime text 3 and atom you can get to any command quickly with apple/ctrl-shift-p, then just start typing the command (fuzzy matching), way quicker than a menu

you can also add custom key bindings, for example, i tied apple-shift-s to compile tabs

```
[
    {  "keys": ["super+shift+d"], "command": "duplicate_line" }
]  
```

**Comment by ralphcallaway** [comment]
closing this out since since st3 provides easy customization of key commands

fyi @OlegForce assuming you're using st3, you'll love the command pallete (`super-shift-p`), i'm a big keyboard guy and running any command without touching the mouse is pretty easy with sublime text
- open command palette (`super-shift-p`)
- start typing desired command with fuzzy search, e.g. mmcp
- click enter

**Comment by orikkers** [comment]
:) thanks, I figured it out, but forgot I had this one opened.
