### ISSUE TITLE
Can't create project from existing folder

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate#440]
Usually when I have another org with a separate branch in git, I would clone the branch into my workspace and create a new mavensmate project from that folder (within sublime text). When I submit my credentials it would accept that and the project is then associated with that org.

This seems to no longer be the case. If I create a mavensmate project from a folder in my workspace and submit my credentials, it will tell me that the project already exists.

Looks like a bug?

![7f6e8687753beb25c415255174a38d08](https://cloud.githubusercontent.com/assets/4478123/7429686/c591a502-effd-11e4-9690-efdfcef221d0.png)

**Comment by ralphcallaway** [comment]
@LKozakewycz i think this workflow could be improved, i.e. prompting to overwrite instead of just shutting down

typically when this happens to me, there is in fact a folder with your project name in that workspace (either an old version of the same project, or something that partially succeeding but didn't complete from a past try), can you double check that's not the case?

ps - the workflow you're describe is what i've always done

previously i would copy the contents of the .config folder (and update some path references) from a second project "i.e. Project2" to get things going. you shouldn't need to do that anymore, but if it is a bug that's an option

**Comment by ralphcallaway** [comment]
@LKozakewycz closing this out given the age of the case, if this is still happening please re-open and update the issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md
