### ISSUE TITLE
Deployment of "unfiled public" Reports fails

### ISSUE THREAD

**Issue by simpleTechs** [joeferraro/MavensMate#45]
When deploying some unfiled public reports from sandbox to production, I get this error in the log:
`An object 'unfiled$public' of type Report was named in package.xml, but was not found in zipped directory`

The UI shows every component I wanted to deploy as "Success", but still the message says "Deployment failed".
I'd would be nice to have the log handy right when sth. wents wrong.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
