### ISSUE TITLE
Just installed - can't connect to salesforce sandbox

### ISSUE THREAD

**Issue by etech0** [joeferraro/MavensMate#457]
Hi

I just installed MavensMate and am trying to set up my first project. I put in a project name, put my salesforce sandbox username (including .testing at the end of the username because that's the name of the sandbox), and my password + sandbox token. I chose Sandbox in the dropdown, but when I try to connect it tells me:

Server raised fault: 'INVALID_LOGIN: Invalid username, password, security token; or user locked out.'

Any idea what I'm doing wrong?

Thanks!

**Comment by aceb694** [comment]
I'm having the same problem.

**Comment by smohyee** [comment]
I'm guessing this issue is more related to your credentials than to Mavensmate, because most other users including myself aren't experiencing this issue.

Here's something you might check for: your sandbox's security token needs to be reset every time you refresh the sandbox. If you're using the same security token from before a refresh, request a new token from within the sandbox and try again.

Alternatively, you can double check your sandbox login credentials by using them on another 3rd party tool, like SF's data loader (which also requires the security token). If your sandbox credentials work on the data loader but not on mavensmate, then I'd say you have a good argument for an MM specific issue.

**Comment by christianbundy** [comment]
Personally, I resolved this problem by setting `loginUrl`, so my `create-project` looks like this:

``` bash
mavensmate new-project <<< '{ "name" : "myproject", "workspace" : "/path/to/workspace", "username" : "foo@bar.com", "password" : "foo", "loginUrl": "https://test.salesforce.com", package: { "ApexClass" : "*" } }'
```

Hopefully this can help someone else in the future!

**Comment by Lvkz** [comment]
Don't know if useful today but found out that you just have to fill the password field as: passwordtoken all together and it will work. :)
