### ISSUE TITLE
improve ux when creating new project

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#474]
do not describe entire org, get high-level metadata then describe individual types as user clicks type folder bc in large orgs, initial describe can take several minutes

**Comment by ralphcallaway** [comment]
@joeferraro when you're doing this would be really good to take a look at the flow for creating a project for a folder that already exists. This workflow is used whenever the code exists in a git repo before, since the folder has to exist prior, or if things get corrupted and you want to recreate the project from scratch.

In theory, you should be able to open the project, create a new project, and the creation flow should be smart enough to recognize that even though the folder already exists in the workspace, it's okay to create a new project.

In my opinion, we could drop the whole workspace concept entirely, it hasn't really been a value for me, since most text editors already have great management for switching and opening projects.

**Comment by ralphcallaway** [comment]
ps - you used to be able to create a project from an existing folder in the workspace, but this no longer appears to work, you have to first move the folder back out of the workspace, create it, and then update any references (i.e. your source control browser) to point to the new location
