### ISSUE TITLE
Explore the re-implementation of project-specific settings

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#490]
i think these should be implemented as a mavensmate-specific json configuration in the project root (generated upon project creation). the challenge here will be re-architecting the way config is detected throughout the core. we're using nconf to manage config, which generates a singleton that can be required in any core module (so super simple to use in its current form). introducing config overrides on a per-project basis will be a challenge.

**Comment by bk-dev** [comment]
Any chance you could provide instructions on how to change project settings (i.e. which files to touch/modify) without going through the entire process via Edit Project -> Project Details -> Update Credentials? We are working on a development process which would require us to be able to switch sandbox contexts from the same MavensMate project/workspace. This is only because git is tracking a single directory. We just want to be able to modify sandbox credentials at a file system level very quickly. Thanks for all that you do! =)
