### ISSUE TITLE
Report Folder not found

### ISSUE THREAD

**Issue by lifewithryan** [joeferraro/MavensMate#57]
I'm not sure if this is a bug or if I am missing something in the process but, I have an org that I've pulled reports down from in an attempt to move them into another org.  These reports are in a subfolder, for the sake of argument, call the folder "My Reports"

When I try to save the report, it fails saying that it cannot find folder:My Reports (e.g. [DEPLOYMENT FAILED]: unpackages/dashboards/My Reports/My_report.report: Cannot find folder:My Reports).  

I was wondering:
A) is there something "special" I need to do to get folders saved to my org?
B) should I be doing this in some other way? (Was hoping I could get away with doing it this way)

Also to note, I couldn't right click on .dashboard, .report, or .reportType extensions and have them available for compile.  I edited my user settings and added them to the recognized extensions and then it worked fine (thereby revealing the folder not found issue I'm reporting).

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
