### ISSUE TITLE
After MavensMate Update, Sublime Text won't find mm_workspace

### ISSUE THREAD

**Issue by tadahh** [joeferraro/MavensMate#576]
Operation Failed: Please ensure mm_workspace is set to existing location(s) on your local drive

is the erorr received when refreshing files from Salesforce Server

**Comment by jordanbaucke** [comment]
I began receiving the same error as well:

```
MavensMate for Sublime Text v6.0.0

[OPERATION FAILED]: Please ensure mm_workspace is set to existing location(s) on your local drive
```

**Comment by Wizardum** [comment]
MavensMate has been rollbacked to the old version (v4) which doesn't depend on an external app.

You can find information about fixing this issue in [here](https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/rollback.md), either by fixing the mm_workspace setting or updating again to the beta version (v7).

I do prefer the latest since I noticed compiling and saving is a lot faster now.

**Comment by gnanadeeptu** [comment]
Hi Joe, I have added MavensMate to my install_prereleases. I still see the same error. May I know if there is anything else i need to do?

**Comment by joeferraro** [comment]
this is a dupe of https://github.com/joeferraro/MavensMate-SublimeText/issues/711. please follow there. thanks!
