### ISSUE TITLE
After rolling back to version V4 , my mavens mate is throwing errors

### ISSUE THREAD

**Issue by sirimudindi** [joeferraro/MavensMate#581]
After rolling back to v4.0.5 , i get this error on my mavens mate , Please ensure mm_workspace is set to existing location(s) on your local drive. Please suggest. What have to be changed in the mm_workspace ?

**Comment by garyspencer** [comment]
There are several issues opened regarding this error with the underlying issue might be.  Please check them for solutions and see if they help you so we don't duplicate errors.

If not, please report back and update your question according to the posting guidelines (we need more info about your system and what version of everything you are using! :smile: )  

https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

Existing issues with possible solutions INCLUDING, BUT NOT LIMITED TO (Please search the issues in all mavensmate repos since they are a bit disjointed at the moment)

https://github.com/joeferraro/MavensMate/issues/576
https://github.com/joeferraro/MavensMate-SublimeText/issues/711

**Comment by Heiberg5** [comment]
So, the MM app (in version 5) handled some delegated tasks, like handling some of these settings previusly in your sublime text mavensmate user settings. On my machine, when my Mavensmate was updated back to version 4, that setting (mm_workspace) was never recreated in my user settings. If you manually recreate it, try using the default settings as guidance, it should work.

**Comment by joeferraro** [comment]
@Heiberg5 is correct. closing for now. thanks!
