### ISSUE TITLE
Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

### ISSUE THREAD

**Issue by sejalgada** [joeferraro/MavensMate#622]
I am using sublime Text 3 and mavenmateapp v0.0.10. 
Whe I try to save I get the error "Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store."

Can you please sort this asap?

**Comment by ralphcallaway** [comment]
@sejalgada can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by sejalgada** [comment]
OS  : Windows 64bit
MavensMate-app version : v0.0.10
MavensMate plugin version : Version 6
Firewall  : No
Salesforce : cs87
Steps: I am not able to save any file. I run into the issue.

**Comment by steals** [comment]
@sejalgada Did you install MavensMate-app separately or it was installed automatically? If you installed it manually you need to uninstall it and re-install the ST Text plugin. Because now you have two incompatible installations as ST plugin version 6 uses old mm api that's installed with the plugin and MM-app from the repo https://github.com/joeferraro/MavensMate-app has a new api that's compatible only with ST plugin version 7

**Comment by ralphcallaway** [comment]
@sejalgada can you try re-creating the project and see if that fixes your issue?

if that doesn't work i'd need some logging info, enable [plugin loggin](https://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging), then repeat the issue then paste the contents of your sublime text console (view -> show console) and the mavensmate log

**Comment by sejalgada** [comment]
@ralphcallaway Thanks for your support. Now I am able to work with Sublime and Mavensmate.
