### ISSUE TITLE
Open Sublime Projects in Atom.io

### ISSUE THREAD

**Issue by ddawson90** [joeferraro/MavensMate#639]
I am really keen to begin using Atom.io instead of Sublime despite the plugin still being in beta.

I have a lot of project files locally that are configured in Sublime, Eclipse and Source Tree and I really don't want to have to rebuild my workspace.

I have been trying to import these projects into Atom, but when I open the project folder and right click I do not have the option to create a project like Sublime Text, I only have the option "Delete from server".

Also I have set the workspace in my Global Settings (MM app) and I know it works because the new projects are created there. But when I try to open these projects in Atom the list is empty (probably as they only have sublime config files and have not yet been configured in Atom).

Any direction as to how opening these projects in Atom.io?

**Comment by e02d96ec16** [comment]
Have you set up the atom path in the MM settings?
It must always be updated after an atom update, because the atom updates will go into their own version folders and possibly delete the previous location.
At least, that's what happens in Windows.
I tried setting the path to `C:\Users\e02d96ec16\AppData\Local\atom\Update.exe --processStart atom.exe`, which supposedly always starts the latest version, but it won't work; I think MM really wants an `atom.exe`.

![capture16](https://cloud.githubusercontent.com/assets/14942417/13072965/ff6d23ca-d493-11e5-91e2-87e177714a0c.PNG)
![capture15](https://cloud.githubusercontent.com/assets/14942417/13072970/095e5c5a-d494-11e5-97a4-c0c155bff771.PNG)

**Comment by ddawson90** [comment]
Yes that was the issue - the atom.exe was being troublesome. Thansk for your assistance!
