### ISSUE TITLE
Enhancement: Download user defined objects and their definitions

### ISSUE THREAD

**Issue by iDev0urer** [joeferraro/MavensMate#651]
Most IDE's have the ability to download and store a list of user defined objects and their definitions for use with auto complete. For example I have an object `Project__c` in my org which has several of it's own fields. The Idea plugin Illuminated Cloud downloads all of the object definitions as xml files and parses them, allowing auto complete access to them.

**Comment by ralphcallaway** [comment]
so mavensmate will do auto-complete for field names on user objects and methods on classes today, although it can be finicky

if you're expecting something to autocomplete and it's not you can try cleaning the project, or running the refresh apex symbols command, usually if auto-complete is having trouble it's because the data it's using is stale (e.g. you just created a new object/class on the server that mavensmate doesn't know about yet)

closing since the enhancement is already in there, but please create another ticket if you're having a specific issue, or a specific enhancement
