### ISSUE TITLE
Invalid project directory in workspace configuration throws exception

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#674]
Error initializing project: ENOENT: no such file or directory, scandir '/invalid/path/here'

**Comment by MattBradleyRoberts** [comment]
Having a similar issue I suspect.

Due to the TLS thing finally going live, I had to install ST3 and the MavensMate app (having previously used ST2 and the MM plugin).

I have a mavens project created, but I've replaced the src folder with a symlink to point to my git src directory. This used to work fine in the ST2/Plugin world, but now results in:

<img width="554" alt="screen shot 2016-06-15 at 13 39 51" src="https://cloud.githubusercontent.com/assets/8088121/16080089/fcb8a84c-32fe-11e6-81d2-6c96458e90c6.png">

Is this the same bug? Or am I barking up the wrong tree?

Any help would be very much appreciated. Thanks.
