### ISSUE TITLE
Email Template folders from a managed package are not displayed, even when setting "mm_ignore_managed_metadata" to false

### ISSUE THREAD

**Issue by rajesh-k** [joeferraro/MavensMate#71]
Mavensmate App Version: 0.35.1
MavensMate for Sublime Text v3.0.4
Sublime Text version 3047

We have an email template folder that is part of a managed packaged from a 3rd party. In this folder, we have our own templates as well. In Mavensmate meta-data selection window, I don't see the managed package email template folder. Are there plans to show them in the future?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
