### ISSUE TITLE
[ERROR]: Request to the local MavensMate server failed when trying to create New Project

### ISSUE THREAD

**Issue by imtzcb** [joeferraro/MavensMate#740]
I've searched for this error but most pages found by Google search no longer exist. I tried installing a newer version of MavensMate desktop (v0.0.11-beta.4) but no luck so far. 

Any help will be greatly appreciated. Thanks in advance

Result: [ERROR]: Request to the local MavensMate server failed. please ensure MavensMate Desktop is installed and running. For more information, please visit https://github.com/joeferraro/MavensMate/tree/master/docs

* **MavensMate Version**: Mavensmate for Sublime Text v7.0.1

* **Editor**:Sublime 3

* **Platform/Version**: Windows 7 64-bit

* **Proxy Details**: No

* **Salesforce Server**: na11

 
Mavensmate > Project > New Project 

Result: [ERROR]: Request to the local MavensMate server failed. please ensure MavensMate Desktop is installed and running. For more information, please visit https://github.com/joeferraro/MavensMate/tree/master/docs

**Comment by joeferraro** [comment]
Do you have MavensMate Desktop running?

**Comment by imtzcb** [comment]
Yes, and I just opened it. I am not familiar with the desktop. When opening settings I thought it was a help page that I would use to update the settings file using Sublime. I just realized that that's where I'm supposed to set the mm_workspace. 

Also, whenever I created a new Apex class with Sublime Mavensmate it would open small windows within sublime to enter the apex class details. Now it opens the desktop.

Are all these changes coming from the beta release that I just installed  (desktop v0.0.11-beta.4)? If so, I'll try to figure out how to use it from now on. Or am I doing something wrong?

I'm still confused as to why it stopped working. Is there a log I can grab and post it here?

**Comment by joeferraro** [comment]
@imtzcb Salesforce recently stopped supporting TLS 1.0, which is the transport method used by the old version of MavensMate for Sublime Text. Since I wrote that plugin a few years, ago, 2 other editor plugins ([Visual Studio Code](https://github.com/joeferraro/MavensMate-VisualStudioCode) and [Atom](https://github.com/joeferraro/MavensMate-Atom)) have joined the MavensMate ecosystem. Instead of writing unique code for each plugin, [MavensMate Desktop](https://github.com/joeferraro/MavensMate-Desktop) is a common server (that uses TLS 1.1) for any of these plugins to communicate with. This way, we code all the file system and Salesforce API interactions one time and run a local server on your machine that any of our plugins can communicate with ([see this diagram](https://github.com/joeferraro/MavensMate#mavensmate---open-source-ides-for-salesforce)). So, when you're developing Salesforce applications in one of our supported editors, MavensMate Desktop has to be running. Sure, it's another thing you have to download, but it greatly simplifies life for those building and maintaining MavensMate. I hope this helps clarify for you. If you have any other issues, don't hesitate to post them on this project and I'll look into it. Thanks! -Joe

**Comment by imtzcb** [comment]
Very nice! Thanks a lot for taking the time to answer all my questions. 

I started using Mavensmate a few weeks ago and it has really helped me.
