### ISSUE TITLE
Lightning Files overwrite when multiple users working on same files

### ISSUE THREAD

**Issue by mikepaisner** [joeferraro/MavensMate#905]
We have multiple developers working on a Lightning Application using MavensMate.
On multiple occasions, lightning files have been overwritten when one person tries to work on a file that another person has worked on.

Occasionally, a warning will pop up to refresh the file, but often no warning is given and the old local version of a file ends up overwriting the most current version on the server.

All the developers prefer to work in MavensMate, but overwriting files is making it very difficult.

Mike Paisner

* **MavensMate Desktop Version**: MM App V0.0.10

* **Editor**: Sublime Build 3126

* **MavensMate Plugin Version**:

* **Platform/Version**: Windows 7 64 bit

* **Proxy Details**:

* **Salesforce API Version**: 34.0

* **Salesforce Server**: CS 42

**Comment by kidtsunami** [comment]
I'm sorry, but we can't do much else since we rely on Salesforce to inform us of any conflicts.

We highly recommend that you follow Salesforce best practices and not have a whole team of people working on the same files in the same org.

https://resources.docs.salesforce.com/sfdc/pdf/salesforce_development_lifecycle.pdf
